<?php  ?>
    <div class="footer-160">

        <div class="logo col-6">
            <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/logo.png'); ?>" width="214" height="116"/>
        </div>
        <div class="col-6">
            <p>¡Entérate de mucho más!</p>
            <div>
                <a><img src='<?php echo $this->getViewFileUrl('images/social/instagram.png'); ?>' alt="Instagram"></a>
                <a><img src='<?php echo $this->getViewFileUrl('images/social/twitter.png'); ?>' alt="Twitter"></a>
                <a><img src='<?php echo $this->getViewFileUrl('images/social/facebook.png'); ?>' alt="Facebook"></a>
        
            </div>
        </div>

    </div>