<div class="form1-160"> 
    <div class="form-container">
        <div class="logo-160">
            <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/logo.png');?>" width="164" height="89"/>
        </div>

        <div class="col-6">
            <div class="form-left">
                <h1>
                    ¡Haz parte de una <span>compañía global!</span>
                </h1>
                <p>
                    Sé uno de los 160Developers que estamos buscando y haz parte de un equipo global.
                </p>
                <p>
                    ¿Crees que puedes ser uno de ellos?
                </p>
                <p>
                    <span class="accent">¡Descúbrelo!</span>
                </p>
            </div>
        </div><div
            class="col-6">
            <div class="form-right">
                <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Insergio_JobForm::form.phtml")->toHtml(); ?>
            </div>
        </div>
    </div>

</div>