<div class="header-160">

    <div class="buttons-container">

        <div class="widget-left">
            <a class="url-link btn item-block">
                ES
            </a>
            <p>-</p>
            <a class=" btn item-block">
                EN
            </a>
        </div>


        <div class="widget-right">
            <a class="onpage-link btn item-block">
                Vacantes
            </a>
        </div>

        <div class="widget-right">
            <a class="onpage-link btn item-block">
                Trabajo Ideal
            </a>
        </div>

        <div class="widget-right">
            <a class="onpage-link btn item-block">
                Referidos
            </a>
        </div>

    </div>
 
</div>